name: Download Repository to Remote Server

on:
  push:
    branches: [ main ]

jobs:
  download-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH connect and download repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}

          script: |
            git clone $1
            cd $2
            git pull origin main
          args: |
            ${{ github.url }}
            ${{ github.repository_name }}
