name: SSH File Change Workflow

on:
  push:
    branches: [ main ]

jobs:
  change-files-on-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH connect and change files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_KEY }}
          script: |
            scp /home/student/test/test.go ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/home/student/test/
