name: SSH File Change Workflow

on:
  push:
    branches: [ main ]

jobs:
  change-files-on-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH connect and change files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /path/to/your/project/on/server
            # Replace these with your actual commands
            echo "Making changes to files..."
            touch new_file.txt 
            echo "Changes made!"
